language: csharp
solution: MonitoringAgent.sln
mono: none
dotnet: 2.0.0
script:
 - dotnet restore
 - dotnet publish -c Release
 - sudo dotnet test /home/travis/build/avalko/monitoring-agent/MonitoringAgent.Tests/MonitoringAgent.Tests.csproj -c Release
